name: Build Linux (x64 & ARM64)

on:
  repository_dispatch:
    types: [build-linux-command]
  workflow_dispatch:

jobs:
  build:
    if: github.event.client_payload.slash_command.command == 'build-linux'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            platform_name: "x64 (AMD64)"
            artifact_suffix: "linux-x64"
          - os: ubuntu-latest  # Cross-compile ARM64 from x64 runner
            arch: arm64
            platform_name: "ARM64"
            artifact_suffix: "linux-arm64"
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Add reaction
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reactions: eyes
    
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}
        lfs: true
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
    
    - name: Get version info
      id: version
      run: |
        # Get the short commit SHA
        SHORT_SHA=$(echo ${{ github.event.client_payload.pull_request.head.sha }} | cut -c1-7)
        # Get the PR number
        PR_NUMBER=${{ github.event.client_payload.pull_request.number }}
        # Create version string
        VERSION="pr-${PR_NUMBER}-${SHORT_SHA}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
    
    - name: Build for Linux ${{ matrix.platform_name }}
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
        CGO_ENABLED: 1
      run: |
        # Install cross-compilation tools for ARM64 if needed
        if [ "${{ matrix.arch }}" = "arm64" ]; then
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          export CC=aarch64-linux-gnu-gcc
        fi
        
        mkdir -p dist
        go build -ldflags="-s -w" -o dist/time-${{ matrix.artifact_suffix }} ./cmd/time
        
        # Verify the binary was built correctly
        file dist/time-${{ matrix.artifact_suffix }}
        ls -la dist/
    
    - name: Make binary executable
      run: |
        chmod +x dist/time-${{ matrix.artifact_suffix }}
    
    - name: Create archive
      run: |
        cd dist
        tar -czf time-${{ matrix.artifact_suffix }}-${{ steps.version.outputs.version }}.tar.gz time-${{ matrix.artifact_suffix }}
        ls -la
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: time-${{ matrix.artifact_suffix }}-${{ steps.version.outputs.version }}
        path: dist/time-${{ matrix.artifact_suffix }}-${{ steps.version.outputs.version }}.tar.gz
        retention-days: 30
    
    - name: Add success reaction
      if: success()
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reactions: rocket
    
    - name: Add failure reaction
      if: failure()
      uses: peter-evans/create-or-update-comment@v4
      with:
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reactions: confused

  summary:
    if: github.event.client_payload.slash_command.command == 'build-linux' && always()
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Get version info
      id: version
      run: |
        # Get the short commit SHA
        SHORT_SHA=$(echo ${{ github.event.client_payload.pull_request.head.sha }} | cut -c1-7)
        # Get the PR number
        PR_NUMBER=${{ github.event.client_payload.pull_request.number }}
        # Create version string
        VERSION="pr-${PR_NUMBER}-${SHORT_SHA}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "pr_number=${PR_NUMBER}" >> $GITHUB_OUTPUT
    
    - name: Post build summary
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.client_payload.pull_request.number }}
        body: |
          ## 🐧 Linux Build Summary
          
          **Build Details:**
          - **Version:** `${{ steps.version.outputs.version }}`
          - **Commit:** `${{ steps.version.outputs.short_sha }}`
          - **Overall Status:** ${{ needs.build.result == 'success' && '✅ Success' || needs.build.result == 'failure' && '❌ Failed' || '⚠️ Completed with issues' }}
          
          **Downloads:**
          
          | Platform | Architecture | Download |
          |----------|-------------|----------|
          | Linux | x64 (AMD64) | [time-linux-x64-${{ steps.version.outputs.version }}.tar.gz](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) |
          | Linux | ARM64 | [time-linux-arm64-${{ steps.version.outputs.version }}.tar.gz](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) |
          
          > **Note:** Click the download links above, then scroll down to the "Artifacts" section to download the builds. Only successful builds will have downloadable artifacts.
          
          **Quick Start:**
          1. Download the appropriate tar.gz file for your Linux architecture
          2. Extract the archive: `tar -xzf time-linux-*.tar.gz`
          3. Make executable (if needed): `chmod +x time-linux-*`
          4. Run: `./time-linux-x64 --help` or `./time-linux-arm64 --help`
          
          ${{ needs.build.result == 'failure' && '**⚠️ Some builds failed.** Check the [workflow run](' || '' }}${{ needs.build.result == 'failure' && github.server_url || '' }}${{ needs.build.result == 'failure' && '/' || '' }}${{ needs.build.result == 'failure' && github.repository || '' }}${{ needs.build.result == 'failure' && '/actions/runs/' || '' }}${{ needs.build.result == 'failure' && github.run_id || '' }}${{ needs.build.result == 'failure' && ') for details.' || '' }}
          
          ---
          *Builds triggered by `/build-linux` command*
