name: Cleanup PR Container Images

on:
  pull_request:
    types: [closed]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nakedsoftware/time

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete PR container images
      env:
        PR_NUMBER: ${{ github.event.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Cleaning up container images for PR #${PR_NUMBER}"
        
        # Get all package versions for the image
        PACKAGE_VERSIONS=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/orgs/nakedsoftware/packages/container/time/versions" \
          --jq '.[] | select(.metadata.container.tags[]? | test("^pr-'${PR_NUMBER}'$")) | .id')
        
        if [ -n "$PACKAGE_VERSIONS" ]; then
          echo "Found package versions to delete:"
          echo "$PACKAGE_VERSIONS"
          
          # Delete each version
          echo "$PACKAGE_VERSIONS" | while read -r version_id; do
            if [ -n "$version_id" ]; then
              echo "Deleting package version: $version_id"
              gh api \
                --method DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "/orgs/nakedsoftware/packages/container/time/versions/$version_id" || true
            fi
          done
          
          echo "Cleanup completed for PR #${PR_NUMBER}"
        else
          echo "No container images found for PR #${PR_NUMBER}"
        fi