name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  slashCommandDispatch:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/build-macos')
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            build-macos
          permission: write
          issue-type: pull-request
          repository: ${{ github.repository }}